name: convae_lstm
num_classes: 6
beta: 0.030589952331743383
#lstm_weigts: [1.5, 1.5, 1.5, 0.6, 0.6, 1.5]

embed: 
  _target_: net.blocks.conv_deconv.ConvBlock
  in_channels: 9
  out_channels: 256
  pool_type: "avg"
  kernel_size: 11
  pool_size: 2
  pool_stride: 2
  stride: 2

decoder:
  _target_: net.blocks.conv_deconv.DeconvBlock1D
  out_channels: 9
  kernel_size: 4
  stride: 4
  output_padding: 0
  padding: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0014673859014462246
  weight_decay:  0.0009369161140381144

rnn_block:
  _target_: net.blocks.lstm.LSTMBlock 
  hidden_size: 128  
  num_layers: 2     
  dropout: 0.5974215509451941
  bidirectional: true

trainer:
  max_epochs: 95
  log_every_n_steps: 10
  
callbacks:
  patience_AE: 20
  patience_LSTM: 39

dataset:
  data_dir: "${oc.env:PWD}/data"
  batch_size: 32
  val_split: 0.3
